"""Portfolio content. Edit this file, then run:  python3 extract.py && python3 build.py

SOURCES     – the decks the imagery is cut from.
PROJECTS    – ordered. Each page entry is (source, page_number, caption, [tags]).
              extract.py cuts each deck page into its individual artworks, so one
              page entry can produce several images on the site.
"""

NAME = "Polina Vasilyeva"
ROLE = "Senior Product and Interaction Designer"
EMAIL = "vasilievapolli@gmail.com"
PHONE = "203 909 8496"
LOCATION = "New York / Madrid"
LINKEDIN = "https://www.linkedin.com/in/polina-vasilyeva-265aa031/"

ABOUT = [
    "I am a designer focused on UX/UI and Product Design, Digital Brand Experiences and Identity and Digital Accessibility.",
    "At the moment, I'm living and working in New York as a Senior Product and Visual Designer. I hold a Master's degree in Design and Human Computer Interaction from Yale School of Art '17 and a Bachelor in Graphic Design from Gerrit Rietveld Academy, Amsterdam.",
    "I had the opportunity to work as a Senior Designer and lead both junior brand and product designers at companies like Apple, Google, Optum and United Healthcare, Verizon, Frog Design, Wolff Olins and Apartamento Studios. My expertise is in design systems and experiences that are accessible, viable and tailored to business needs. I'm passionate about future oriented research and concept development in digital technology.",
]

CLIENTS = ["PayPal", "Apple", "Optum", "Google / Fitbit", "McKinsey", "Verizon",
           "Alexander Wang", "WSJ", "Haworth", "Apartamento Studios",
           "frog design",
           "Florida Blue", "Wolff Olins", "HUGE", "Chobani", "Furniture.com",
           "Tomo", "Pratt Institute"]

TEACHING = [
    ("NYU", "Visiting Critic, 2021 to present"),
    ("Pratt Institute", "Adjunct Professor, 2017 to 2020"),
    ("The New School", "Adjunct Professor, 2017 to 2018"),
    ("RISD", "Visiting Critic, 2017 to 2021"),
]

EDUCATION = [
    ("Yale School of Art", "MFA, Graphic and Digital Product Design, 2015 to 2017"),
    ("Gerrit Rietveld Academie", "BFA, Graphic and Interaction Design, 2010 to 2015"),
]

INTRO = ("Selected work in product, web, brand, and editorial design for "
         "Verizon, Haworth, Alexander Wang, Chobani, and Florida Blue.")

# The recent product work is not shown here; say so rather than let the hero
# promise names the grid does not contain.
INTRO_NOTE = ("Recent product design for PayPal, Apple, Optum, and Google is "
              "described on the <a href=\"about.html\">about page</a>.")

SOURCES = {
    "A": "/Users/polinavasilyeva/Downloads/Portfolio_Polina_Vasilyeva_2026.pdf",
    "B": "/Users/polinavasilyeva/Downloads/"
         "Polina_Vasilyeva_2026_Senior_Digital_Interactive_Designer.pdf",
    "C": "/Users/polinavasilyeva/Desktop/Verizon portfolio .pdf",
    "D": "/Users/polinavasilyeva/Desktop/Polina_Vasilyeva_2023_Watson_portfolio.pdf",
    "E": "source/_decks/haworth-brand-guidelines.pdf",
    "F": "source/_decks/furniture-final-design.pdf",
    "G": "source/_decks/furniture-color-typography.pdf",
    "H": "source/_decks/furniture-final-design-full.pdf",
    "I": "source/_decks/verizon-retail-signage.pdf",
}

FILTERS = [
    ("all", "all"),
    ("web", "web"),
    ("mobile", "mobile"),
    ("ecommerce", "ecommerce"),
    ("brand", "brand"),
    ("product", "ux and product"),
    ("editorial", "editorial"),
    ("strategy", "strategy"),
    ("social", "social"),
]

# The overview section at the top of the index, one image per project.
GROUPS = [
    ("brand",   "Brand and campaign"),
    ("product", "Product and web"),
    ("book",    "Books and print"),
    ("type",    "Type"),
]

PROJECTS = [
 {
  "slug": "verizon", "title": "Verizon",
  "year": "2022 to 2023",
  # The signage slices come off pages of different heights; one width
  # sets them level, two to a row.
  "piece_width": {"c002-1": 70,
                  "i001": 27, "drop12": 32, "drop09": 30,
                  "c003-1": 48, "c003-2": 48, "c004-1": 48, "c004-2": 48},
  # The logo slide carries the deck's own small header top-left; it comes
  # off, and the same again off the foot so the mark stays centred.
  # Framed like Haworth's mark: the mark an eighth of the height,
  # centred, at one aspect, so the two covers read as a pair.
  "piece_crop": {"i017": (0.004, 0.0015, 0.004, 0.0015),
                 "c002-1": (0, 0, 0.145, 0),
                 "a025": (0.122, 0.058, 0.130, 0.059)},
  "drops_first": True,
  "lead": ["a025", "drop06", "drop07", "drop09", "i001", "i011",
           "c002-1"],
  "before_decks": (["i0%02d" % n for n in (3, 5, 6, 7, 8, 9, 10, 11, 17, 18)]
                   + ["c003-1", "c003-2", "c004-1", "c004-2"]),
  "keep_always": ["i0%02d" % n for n in (1, 3, 5, 6, 7, 8, 9, 10, 11, 17, 18)],
  "cover": "a025",
  "group": "brand", "short": "Retail and brand design",
  "meta": "Verizon, Senior Design Consultant, 2022 to 2023, Retail and Brand Design",
  "desc": ["–Ran research across digital and retail touchpoints to identify opportunities to improve customer experience and brand look and feel.",
           "–Unified fragmented design standards spanning brand guidelines, retail, and UX into a single simplified system.",
           "–Audited and updated design assets and customer-facing experiences against accessibility best practices.",
           "–Streamlining these standards raised designer productivity, shortened retail project turnaround, and improved print quality."],
  "pages": [
    # The deck's own title slide carries the wordmark on the slide ground, and
    # the Retail SEM title exists only at 1020px – too small to be a cover.
    # The Retail SEM working deck, published whole: the system, the
    # wayfinding tiers, and the store as it was built and as it will be.
    # The deck's own logo slide, black ground, no footer: the cover.
    ("A", 25, "Verizon – the mark", ["brand"], {"crop": False, "split": False}),
    ("C", 2,  "Printed assets for national retail",
              ["brand"], {"rows": True, "keep": [1]}),
    ("C", 3,  ["Ultra signage – the counter unit",
               "The Spanish plans wall"], ["brand"],
              {"slices": [(0.024, 0.404), (0.404, 0.914)]}),
    ("C", 4,  ["The light box",
               "The Ultra table"], ["brand"],
              {"slices": [(0.024, 0.331), (0.404, 0.914)]}),
    ("A", 32, "Growth strategy deck", ["strategy"]),
    # The retail signage artwork itself, a banner to a page.
    ("I", 1, "The price sheet", ["brand"],
     {"crop": False, "split": False}),
    ("I", 3, "The reliability strip", ["brand"],
     {"crop": False, "split": False}),
    ("I", 5, "The Unlimited plans strip", ["brand"],
     {"crop": False, "split": False}),
    ("I", 6, "The Ultra strip", ["brand"],
     {"crop": False, "split": False}),
    ("I", 7, "The price strip", ["brand"],
     {"crop": False, "split": False}),
    ("I", 8, "The fastest 5G wall", ["brand"],
     {"crop": False, "split": False}),
    ("I", 9, "The home internet wall", ["brand"],
     {"crop": False, "split": False}),
    ("I", 10, "The Ultra Wideband wall", ["brand"],
     {"crop": False, "split": False}),
    ("I", 11, "The Disney Bundle wall", ["brand"],
     {"crop": False, "split": False}),
    ("I", 17, "The wide Ultra wall", ["brand"],
     {"crop": False, "split": False}),
    ("I", 18, "The more places strip", ["brand"],
     {"crop": False, "split": False}),
    ("IMG", "verizon-sem/p02.jpg", "Agenda, the retail reset", ["brand", "strategy"], {"crop": False, "split": False}),
    ("IMG", "verizon-sem/p04.jpg", "Optimizing the retail design system", ["strategy"], {"crop": False, "split": False}),
    ("IMG", "verizon-sem/p05.jpg", "Towards a responsive retail environment", ["strategy"], {"crop": False, "split": False}),
    ("IMG", "verizon-sem/p07.jpg", "The roadmap", ["strategy"], {"crop": False, "split": False}),
    ("IMG", "verizon-sem/p09.jpg", "Entry", ["brand"], {"crop": False, "split": False}),
    ("IMG", "verizon-sem/p10.jpg", "The floor, looking in", ["brand"], {"crop": False, "split": False}),
    ("IMG", "verizon-sem/p11.jpg", "The floor, with the wall behind it", ["brand"], {"crop": False, "split": False}),
    ("IMG", "verizon-sem/p12.jpg", "Wayfinding", ["brand"], {"crop": False, "split": False}),
    ("IMG", "verizon-sem/p13.jpg", "Three tiers of wayfinding in the store", ["brand"], {"crop": False, "split": False}),
    ("IMG", "verizon-sem/p14.jpg", "Back Wall", ["brand"], {"crop": False, "split": False}),
    ("IMG", "verizon-sem/p17.jpg", "Business", ["brand"], {"crop": False, "split": False}),
    ("IMG", "verizon-sem/p18.jpg", "The Business bay and its aisle fixture", ["brand"], {"crop": False, "split": False}),
    ("IMG", "verizon-sem/p19.jpg", "Live Try", ["brand"], {"crop": False, "split": False}),
    ("IMG", "verizon-sem/p20.jpg", "Live Try – the wall without the gradient", ["brand"], {"crop": False, "split": False}),
    ("IMG", "verizon-sem/p23.jpg", "Aisle Fixtures", ["brand"], {"crop": False, "split": False}),
    ("IMG", "verizon-sem/p24.jpg", "Aisle fixtures, the frame", ["brand"], {"crop": False, "split": False}),
    ("IMG", "verizon-sem/p25.jpg", "Aisle headers, by category", ["brand", "editorial"], {"crop": False, "split": False}),
    ("IMG", "verizon-sem/p27.jpg", "Future state – the grey back wall today", ["brand"], {"crop": False, "split": False}),
    ("IMG", "verizon-sem/p28.jpg", "Future state – digital carried through", ["brand"], {"crop": False, "split": False}),
    ("IMG", "verizon-sem/p29.jpg", "The Home wall", ["brand"], {"crop": False, "split": False}),
    ("IMG", "verizon-sem/p30.jpg", "The floor from the entry", ["brand"], {"crop": False, "split": False}),
    ("IMG", "verizon-sem/p31.jpg", "Digital replaces print at Live Try", ["brand", "product"], {"crop": False, "split": False}),
    ("IMG", "verizon-sem/p32.jpg", "The collaboration table", ["brand"], {"crop": False, "split": False}),
    ("IMG", "verizon-sem/p33.jpg", "The floor, wide", ["brand"], {"crop": False, "split": False}),
    ("IMG", "verizon-sem/p34.jpg", "Express Pickup Lockers and the Business wall", ["brand"], {"crop": False, "split": False}),
  ],
 },
 {
  "slug": "haworth", "title": "Haworth",
  "year": "2019",
  # The logo slide reads tighter than 16:9: the wordmark sits in a
  # narrower field, so the slide ground is taken in from both sides.
  # The slide carries its own header and footer in small type; the mark
  # alone is the cover, so both bands come off.
    # The identity opens the project, then the work, then the brand book that
  # documents it. Naming the openers keeps them ahead of the drop folder.
  "drops_first": True,
  "lead": ["b062", "e016", "collection-lockup", "e077", "a059", "a060",
           "social-five-screens", "b064-2", "b065-1", "b065-2", "b066",
           "b068-1", "b068-2"],
  "before_decks": ["haworth-opening-title", "haworth-motion"],
"keep_always": ["e016", "e077"],
  "piece_crop": {"b062": (0.310, 0.271, 0.304, 0.273),
                 "e016": (0.0964, 0.1816, 0.3797, 0.1996),
                 "collection-lockup": (0.242, 0.1955, 0.242, 0.1955)},
  # The research pages are spreads of type; two to a row keeps them
  # readable without letting one fill the measure alone.
  "piece_width": {"social-five-screens": 100,
                  "drop05": 48, "drop06": 48, "drop07": 48,
                  "a059": 48, "a060": 48, "b064-2": 30, "b065-1": 30, "b065-2": 30},
  "cover": "b062",
  "group": "brand", "short": "Brand and online store design",
  "meta": "Haworth, with Apartamento Studios, Brand and Online Store Design",
  "desc": ["–Led the rebrand of Haworth, a leading office furniture manufacturer, developing the brand narrative, collateral, and digital strategy that repositioned the company as a premium office solutions provider rather than a furniture manufacturer.",
           "–Partnered with Haworth's in-house business strategist to align verbal and visual language with the company's cultural and sales strategy goals and target audiences.",
           "–Built flexible, scalable brand systems and guidelines for Haworth's in-house design and marketing teams, optimizing workflow and increasing efficiency, brand consistency, and brand recognition.",
           "–Developed a digital marketing campaign including social media advertising and digital asset production guidelines – increased online conversions by 15%.",
           "–Designed environmental signage for Haworth showrooms and exhibition graphics for NeoCon; authored guidelines for print advertising, brochures, and magazines.",
           "–Oversaw brand application, UX, and UI for Haworth's e-commerce website.",
           "–Outcome: market repositioning, new customer acquisition, and increased sales."],
  "pages": [
    ("B", 62, "Haworth – logo design", ["brand"], {"crop": False}),
    ("E", 16, "Haworth – the logotype on white", ["brand"], {"crop": False, "split": False}),
    ("IMG", "haworth/collection-lockup.png", "Haworth Collection lockup on navy",
     ["brand"], {"crop": False}),
    ("E", 77, "Business cards, standard and bilingual",
     ["brand"], {"crop": False, "split": False}),
    ("A", 59, "Haworth.com homepage – Inspired Design", ["ecommerce", "web"],
     {"dechrome": True, "span": 6}),
    ("A", 60, "Editorial modules – workplace research stories", ["ecommerce", "web"],
     {"dechrome": True, "span": 6}),
    ("IMG", "haworth/social-five-screens.png",
     "Instagram posts and stories", ["social"],
     {"crop": False, "split": False, "span": 12}),

    # b063 and the first half of b064 are dropped: one repeats the shoot, the
    # other carries the "Art Direction" divider band across its foot.
    ("B", 64, "New York headquarters – art direction", ["brand"], {"keep": [2]}),
    ("B", 65, "Apartamento Studios – art direction", ["brand"]),
    ("B", 66, "Designing the Workplace for Innovation – print", ["editorial"]),
    # Both pieces repeat what the folder holds: drop04 and drop03.
    ("B", 68, "Interior Design Hall of Fame Awards – print", ["editorial"]),
    ("E", 5, "Brand book – brand strategy", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 6, "Brand book – brand strategy", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 7, "Brand book – brand strategy", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 8, "Brand book – brand strategy", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 9, "Brand book – brand strategy", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 10, "Brand book – brand strategy", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 12, "Brand book – visual identity", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 13, "Brand book – visual identity", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 15, "Brand book – the logotype", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 17, "Brand book – the logotype", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 18, "Brand book – the logotype", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 19, "Brand book – the logotype", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 20, "Brand book – the logotype", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 21, "Brand book – the logotype", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 22, "Brand book – the logotype", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 23, "Brand book – the logotype", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 24, "Brand book – the logotype", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 25, "Brand book – the logotype", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 26, "Brand book – typography", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 27, "Brand book – typography", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 28, "Brand book – colour", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 29, "Brand book – colour", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 30, "Brand book – colour", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 31, "Brand book – colour", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 32, "Brand book – colour", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 33, "Brand book – colour", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 34, "Brand book – colour", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 35, "Brand book – colour", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 36, "Brand book – colour", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 39, "Brand book – the layout system", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 40, "Brand book – the layout system", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 41, "Brand book – the layout system", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 42, "Brand book – the layout system", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 43, "Brand book – the layout system", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 44, "Brand book – the layout system", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 45, "Brand book – the layout system", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 46, "Brand book – the layout system", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 47, "Brand book – the layout system", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 48, "Brand book – the layout system", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 50, "Brand book – art direction", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 51, "Brand book – art direction", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 52, "Brand book – art direction", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 53, "Brand book – art direction", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 54, "Brand book – art direction", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 55, "Brand book – art direction", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 56, "Brand book – art direction", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 57, "Brand book – art direction", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 58, "Brand book – art direction", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 59, "Brand book – art direction", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 60, "Brand book – art direction", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 61, "Brand book – art direction", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 62, "Brand book – art direction", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 63, "Brand book – art direction", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 64, "Brand book – art direction", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 65, "Brand book – art direction", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 66, "Brand book – art direction", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 68, "Brand book – verbal identity", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 69, "Brand book – verbal identity", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 70, "Brand book – verbal identity", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 71, "Brand book – verbal identity", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 72, "Brand book – verbal identity", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 76, "Brand book – corporate materials", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 78, "Brand book – corporate materials", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 79, "Brand book – corporate materials", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 80, "Brand book – corporate materials", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 81, "Brand book – corporate materials", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 82, "Brand book – corporate materials", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 83, "Brand book – corporate materials", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 84, "Brand book – corporate materials", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 85, "Brand book – corporate materials", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 86, "Brand book – corporate materials", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 87, "Brand book – corporate materials", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 88, "Brand book – corporate materials", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 89, "Brand book – corporate materials", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 90, "Brand book – corporate materials", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 91, "Brand book – document templates", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 92, "Brand book – document templates", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 93, "Brand book – document templates", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 94, "Brand book – document templates", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 95, "Brand book – document templates", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 96, "Brand book – document templates", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 97, "Brand book – document templates", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 98, "Brand book – document templates", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 99, "Brand book – document templates", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 100, "Brand book – document templates", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 101, "Brand book – document templates", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 102, "Brand book – document templates", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 103, "Brand book – document templates", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 104, "Brand book – document templates", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 105, "Brand book – document templates", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 106, "Brand book – print and premium products", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 107, "Brand book – print and premium products", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 108, "Brand book – print and premium products", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 109, "Brand book – print and premium products", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 110, "Brand book – print and premium products", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("E", 112, "Brand book – digital", ["brand", "editorial"],
     {"crop": False, "split": False, "span": 2}),
    ("VID", "haworth-opening-title.mp4", "Opening title", ["brand"],
     {"src": "/Volumes/Expansion/opening_title_2_HAWORTH.mov",
      "start": 0, "duration": 17.4, "width": 1280, "kbps": 1400}),
    ("VID", "haworth-motion.mp4", "Motion graphics", ["brand"],
     {"src": "/Volumes/Expansion/Motion Graphics HAWORTH_6.mov",
      "start": 0, "duration": 69.2, "width": 1280, "kbps": 1100}),
  ],
 },
 {
  "slug": "alexander-wang", "title": "Alexander Wang",
  # The lockup alone: the slide's own caption line sits below it.
  # The lockup and the mark it is built from, side by side.
  "piece_width": {"b003": 48, "b005": 48,
                  "b031-1": 30, "b031-2": 30, "b033": 30,
                  "b035-1": 30, "b035-2": 30},
  "piece_crop": {"b003": (0.02, 0.088, 0.10, 0.088)},
  "year": "2021 to 2022",
  "cover": "b037",
  "group": "brand", "short": "Brand and packaging design",
  "meta": "Alexander Wang, Senior Designer and Art Director, 2021 to 2022, Brand and Packaging Design",
  "desc": ["–Developed seasonal promotional campaigns (spring, summer, autumn) spanning static and dynamic digital media and print.",
           "–Originated and launched branding, campaign, and packaging design for AW Bodywear.",
           "–Administered and maintained AW e-commerce; designed a dedicated e-commerce site for special offers sales.",
           "–Supported planning and logistics for AW events, and directed PR and social media design and copywriting strategy."],
  "pages": [
    ("B", 3,  "bodywear – brand lockup", ["brand"], {"crop": False}),
    ("B", 5,  "The a mark", ["brand"], {"pad": 0.14}),
    ("B", 13, "Packaging – the Classic Briefs bag", ["brand"], {"split": False}),
    ("IMG", "alexander-wang/spec-sheets.png",
     "Product spec sheets", ["brand"],
     {"crop": False, "split": False}),
    ("IMG", "alexander-wang/classic-briefs-packs.png",
     "Classic Briefs – the three pack formats", ["brand"],
     {"crop": False, "split": False}),
    ("IMG", "alexander-wang/resealable-bags.png",
     "Resealable briefs bags", ["brand"],
     {"crop": False, "split": False}),
    ("IMG", "alexander-wang/retail-display-trays.png",
     "Cartons and pouches on red trays", ["brand"],
     {"crop": False, "split": False}),
    ("IMG", "alexander-wang/display-case.png",
     "Bodywear display case", ["brand"],
     {"crop": False, "split": False}),
    ("B", 14, "Packaging – bag, carton, and box", ["brand"], {"split": False}),
    ("B", 15, "Packaging – red stripe across the range", ["brand"], {"split": False}),
    ("B", 16, "Packaging – range variants", ["brand"], {"split": False}),
    ("B", 17, "Packaging – mylar bags", ["brand"], {"split": False}),
    ("B", 18, "Packaging – clear bags", ["brand"], {"split": False}),
    ("B", 19, "bodywear retail units", ["brand"]),
    ("B", 20, "Art direction for flagship display units", ["brand"]),
    ("B", 21, "Grocery refrigeration displays", ["brand"]),
    ("B", 22, "Flagship display units", ["brand"]),
    ("B", 23, "Flagship display units", ["brand"]),
    ("B", 24, "Flagship display units", ["brand"]),
    ("B", 25, "Flagship display units", ["brand"]),
    ("B", 28, "Tiered display units", ["brand"], {"debg": True, "pad": 0.4}),
    ("B", 29, "Whenever. Wherever. – SM and OOH campaign", ["brand", "social"]),
    ("B", 30, "Everyday activities, a cheeky twist", ["brand", "social"]),
    ("B", 31, "Whenever. Wherever. – shot by Todd Oldham", ["brand"]),
    ("B", 32, "Art direction for SM and OOH", ["brand", "social"]),
    ("B", 33, "3D animation series for social media", ["brand", "social"]),
    ("B", 34, "Intimate wear as outerwear", ["brand"]),
    ("B", 35, "Styling direction for Julia Fox", ["brand"]),
    ("B", 36, "Intimate wear as outerwear", ["brand"]),
    ("B", 37, "Beijing flagship – façade animation", ["brand"]),
    ("VID", "beijing-gradient.mp4",
     "Beijing flagship – the gradient, running", ["brand"],
     {"src": "/Volumes/Expansion/32bpc 2.mp4",
      "start": 190, "duration": 40, "width": 800, "kbps": 450,
      "autoplay": True}),   # only 1MB, and an installation loop wants to run
    ("B", 38, "Beijing flagship – gradient video installation", ["brand"]),
    ("B", 39, "Beijing flagship, gradient installation", ["brand"],
     {"scale": 4.0}),
    ("B", 40, "Retail – video installation, animation", ["brand"]),
    ("B", 41, "Retail – video installation, animation", ["brand"]),
    ("B", 42, "Retail – video installation, animation", ["brand"],
     {"scale": 4.0}),
    ("B", 43, "Retail – video installation, animation", ["brand"]),
    ("B", 44, "Sanya Haitang Bay – 3D catwalk animation", ["brand"]),
    ("B", 45, "Sanya Haitang Bay – storefront", ["brand"]),
    ("B", 46, "New York flagship – 3D avatar", ["brand"]),
    ("B", 47, "Retail – video installation, animation", ["brand"]),
    ("B", 48, "Autumn drop campaign – art direction", ["brand"]),
    ("B", 49, "Email design, with the marketing team", ["brand", "social"]),
    ("B", 52, "SISTERS – campaign identity", ["brand"]),
    ("B", 53, "SISTERS – campaign identity and social assets", ["brand", "social"]),
    ("IMG", "alexander-wang/sisters-teaser.png",
     "SISTERS, teaser", ["brand", "social"],
     {"crop": False}),
    ("IMG", "alexander-wang/sisters-bus-shelter.png",
     "SISTERS, bus shelter poster", ["brand"],
     {"crop": False}),
    ("IMG", "alexander-wang/heiress-bag-3d.png",
     "The Heiress bag – 3D animation stills", ["brand", "social"],
     {"crop": False, "split": False}),
    ("B", 60, "vault – archive sale gate", ["ecommerce", "web"], {"dechrome": True}),
    ("B", 61, "vault – archive shopping grid", ["ecommerce", "web"], {"dechrome": True}),
  ],
 },
 {
  "slug": "wsj", "title": "WSJ",
  "year": "2024",
  # Emails and display units at one width, so the set reads as a set
  # rather than as pieces of different importance.
  "piece_width": {**{f"drop{n:02d}": 23 for n in range(1, 14)},
                  "ad-tall": 23},
  "cover": "ad-tall",
  "group": "brand", "short": "Subscription campaign design",
  "meta": "The Wall Street Journal, Subscription Campaign Design",
  "desc": ["I designed subscription acquisition for The Wall Street Journal across the marketing funnel. Display advertising sits at the top, email in the middle, and the offer pages close. Each stage asks for one thing, and the ask gets more specific as the reader moves down.",
           "One campaign runs at more than one ratio. The masthead holds its relationship to the editorial image and to the offer as the frame changes shape.",
           "The email carries the middle of the funnel. Podcast titles are the subject, one colour to a show. The price becomes the picture rather than a line beside it, a green four and a red one over a field of dollar signs. I set it in Escrow, the paper's own face. The subscribe action and the price sit in a band at the foot of every size."],
  "pages": [
    ("IMG", "wsj/ad-tall.png", "Make Art Feuds Your Business – tall unit",
     ["brand"], {"crop": False}),
  ],
 },
 {
  "slug": "clinique", "title": "Clinique",
  "year": "2020",
  "drop_tags": ["ecommerce", "web"],
  # Four grabs kept the whole Chrome window: tab strip, address bar and
  # a personal bookmarks bar. The page begins about 6.8% down.
  "piece_crop": {"drop05": (0.068, 0, 0, 0), "drop06": (0.068, 0, 0, 0),
                 "drop07": (0.068, 0, 0, 0), "drop08": (0.068, 0, 0, 0)},
  "cover": "drop01",
  "group": "product", "short": "Online store and campaign design",
  "meta": "Clinique, clinique iD, Online Store and Campaign Design",
  "desc": ["I designed the campaign and the online store for clinique iD, a hydrator built in two parts. A base takes a cartridge of concentrate. The product page sells it as an equation, base plus cartridge equals the bottle you end up with.",
           "Each concern has its own colour and its own texture. Green is for irritation, blue for pores and uneven texture, purple for lines and wrinkles, orange for fatigue. A shopper can pick a base and a cartridge without reading a word."],
  "pages": [
    # Everything comes from drop/clinique/.
  ],
 },
 {
  "slug": "chobani", "title": "Chobani",
  "year": "2020",
  "keep_ground": True,
  "piece_width": {f"drop{n:02d}": 100 for n in range(1, 10)},
  "cover": "drop09",
  "group": "product", "short": "Product design and research",
  "meta": "Chobani, Product Design and Research",
  "desc": ["In collaboration with the Chobani team I designed chobani.com and ran the research behind it. Landing systems cover every product line, from Greek Yogurt and Flip through Complete, Less Sugar and Drinks, and foodservice has its own. The recipe library holds a cooking mode that works one step at a time. Product pages carry the nutritional highlights."],
  "pages": [
    # The site pages here were screen grabs of the live site; the component
    # files below carry the same work at the size it was drawn.
  ],
 },
 {
  "slug": "furniture", "title": "Furniture.com",
  "year": "2022",
  # The single mobile screens read as a set when they sit three to a row,
  # the same rhythm as the story slides that show three phones at once.
  "piece_width": {"mobile-set-1": 48, "mobile-set-2": 48, "mobile-set-3": 48},
  "lead": ["f001", "f019"],
  # A hairline of the page white survives on two edges of this slide.
  "piece_crop": {"f004": (0, 0, 0.010, 0.006)},
  "cover": "f012",
  "group": "product", "short": "Web design and digital accessibility",
  "meta": "Furniture.com, with McKinsey and studio Dumbar, 2022, Web Design and Digital Accessibility",
  "desc": ["I designed Furniture.com and its accessibility, with McKinsey and with studio Dumbar. Search drives the shopping experience, from the sofa a shopper starts with to the room they browse it in. A warm identity carries it, with a furniture icon set drawn for the job.",
           "Eight colours carry the furniture categories, one each. Every icon and campaign module sits on that palette, and I checked each against black, white and every neutral base for contrast.",
           "I designed it responsively, from the large screen heroes down to the mobile flows."],
  "pages": [
    ("IMG", "furniture/mobile-set-1.png", "Mobile – home, categories, and the little ones",
     ["mobile"], {"crop": False, "split": False}),
    ("IMG", "furniture/mobile-set-2.png", "Mobile – browse rooms and the living room",
     ["mobile"], {"crop": False, "split": False}),
    ("IMG", "furniture/mobile-set-3.png", "Mobile – the product page and its details",
     ["mobile", "ecommerce"], {"crop": False, "split": False}),
    # Published whole. The black slide ground is the deck's own presentation
    # of the work, not a margin to be trimmed away.
    ("F", 1,  "Find it… – campaign banner", ["brand", "web"], {"crop": False}),
    ("F", 3,  "Everything for your living room – campaign", ["brand", "web"], {"crop": False}),
    ("F", 4,  "Room for the whole family – campaign", ["brand", "web"], {"crop": False}),
    ("F", 12, "Homepage – find your sofa", ["web"], {"crop": False}),
    ("F", 18, "Featured categories, by color", ["web"], {"crop": False}),
    ("F", 19, "Furniture for your little ones", ["web"], {"crop": False}),
    ("F", 21, "Featured – Sofas and Sectionals", ["web", "product"], {"crop": False}),
    ("F", 22, "Browse rooms", ["web"], {"crop": False}),
    ("G", 3,  "Color update – before and after", ["brand"], {"crop": False}),
    ("G", 5,  "Color values – furniture, neutral, and action", ["brand"], {"crop": False}),
    ("G", 6,  "Color contrast, tested across the palette", ["brand"], {"crop": False}),
    ("G", 7,  "Icons and color – category campaign cards", ["brand", "web"], {"crop": False}),
    ("G", 9,  "Typography and spacing spec", ["brand", "editorial"], {"crop": False}),
    ("G", 11, "Hero type – Pangea Medium for the CTA", ["brand"], {"crop": False}),
    ("G", 13, "Hero type – the solid call to action", ["brand"], {"crop": False}),
    ("G", 12, "Hero type on the green ground", ["brand"], {"crop": False}),
    # The fuller cut of the same presentation: the category and product pages,
    # the mobile flows, and the campaign as it ran in social, display and OOH.
    ("H", 1,  "Seating – the category page", ["web"], {"crop": False}),
    ("H", 2,  "Category page – the chair that fits", ["web"], {"crop": False}),
    ("H", 8,  "Highland Sunflower Sofa – product page", ["web", "ecommerce"], {"crop": False}),
    ("H", 9,  "Product page – browse to go", ["web", "ecommerce"], {"crop": False}),
    ("H", 12, "Product page – you may also like", ["web", "ecommerce"], {"crop": False}),
    ("H", 19, "Search it, Find it, Buy it – story set", ["social"], {"crop": False}),
    ("H", 20, "Story set, the second", ["social"], {"crop": False}),
    ("H", 21, "Story set, the third", ["social"], {"crop": False}),
    ("IMG", "furniture/story-set-1.png", "Story set, build your space",
     ["social"], {"crop": False, "split": False}),
    ("H", 24, "The perfect chair for you – story", ["social"], {"crop": False}),
    ("H", 25, "Search it. Find it. Buy it. – story on red", ["social"], {"crop": False}),
    ("H", 26, "Your new sofa is waiting – social post", ["social"], {"crop": False}),
    ("H", 27, "Everything for your bedroom – social post", ["social"], {"crop": False}),
    ("H", 28, "Autumn sale – the icon grid", ["social", "brand"], {"crop": False}),
    ("H", 31, "Display – your new chair is waiting", ["brand", "web"], {"crop": False}),
    ("H", 33, "Display – room for the whole family", ["brand", "web"], {"crop": False}),
    ("H", 37, "Out of home – Search it, Find it, Buy it", ["brand"], {"crop": False}),
    ("H", 39, "Out of home – the second run", ["brand"], {"crop": False}),
  ],
 },
 {
  "slug": "lenka-ilic", "title": "Lenka Ilic",
  "year": "2024",
  "drop_tags": ["brand", "web"],
  # The objects are photographed on their own grounds – felt, concrete, a
  # dark table. Keying those out takes the picture with them.
  "keep_ground": True,
  # The card set is one row of three; nothing sits beside it.
  # The card set and each web pair take a row to themselves.
  "piece_width": {"drop02": 100, "drop03": 100, "drop04": 100, "drop05": 100},
  "cover": "drop01",
  "group": "brand", "short": "Identity and website design",
  "meta": "Lenka Ilic Studio, Identity and Website Design",
  # Everything stated here is on the pieces themselves or on the studio's own
  # pages: the material, the maker, the city, the year of founding.
  "desc": ["I designed the identity and the website for Lenka Ilic Studio, a furniture practice in Miami and New York, and art directed the photography. The studio folds each object from recycled aluminium by hand in Delanson, New York. Each carries a debossed signature and a serial number.",
           "The mark sits in one weight, small in the corner of the page and small on the metal, so the object is what you look at."],
    "sink": ["drop03", "drop04", "drop05"],
"pages": [
    # Everything comes from drop/lenka-ilic/.
  ],
 },
 {
  "slug": "bts-advocaten", "title": "Bektesevic Ter Steeg Advocaten",
  "year": "2026",
  "drop_tags": ["web", "brand"],
  # Two pages, each with its phone, to a row.
  "piece_width": {"drop03": 100, "drop04": 100, "drop05": 100,
                  "drop06": 100},
  "cover": "drop01",
  "group": "product", "short": "Website and identity",
  "meta": "Bektesevic Ter Steeg Advocaten, Website and Identity",
  # The site is designed but the copy on it is the firm's own; nothing here
  # describes the practice beyond what the pages themselves state.
  "desc": ["I designed the website and the identity for Bektesevic Ter Steeg Advocaten, a criminal defence practice in Amsterdam. The wordmark sets the two names in a grotesque and the word <em>advocaten</em> in a serif. The pages hold that pairing. A sentence runs between the two faces, so the emphasis falls inside the line rather than on a heading above it.",
           "Bands of pale blue and white carry the argument down the page. I set the type large enough to read at arm's length. The expertise, lawyers and contact pages take the same structure, on the desktop and on the phone."],
  "pages": [
    # Everything comes from drop/bts-advocaten/.
  ],
 },
 {
  "slug": "florida-blue", "title": "Florida Blue",
  "year": "2018 to 2019",
  "drop_tags": ["product"],
  "cover": "drop04",
  "group": "product", "short": "UI strategy and design",
  "meta": "Florida Blue, with frog design, 2018 to 2019, UX and Visual Design",
  "desc": ["Senior UX/UI and Visual Design Consultant, frog design, 2018 to 2019. Launched intuitive, accessible, and friendly user experience strategies and visual design for frog clients Florida Blue and ADP:",
           "–Led user research, testing; established core UX and visual design principles.",
           "–Delivered cohesive design systems, including visual design libraries and optimized customer experience solutions.",
           "–Conducted accessibility tests to make the design accessible."],
  "pages": [
    # Every piece comes from drop/florida-blue/.

  ],
 },
 {
  "slug": "compass", "title": "Compass",
  "year": "2018",
  # The deck runs one slide to a line at 70% of the measure, which is 40% more
  # than the half page a deck slide normally takes. The business card is the
  # same 40% the other way, since a card is a small object.
  # drop09 arrived inside a PDF viewer's artboard, but only the foot of it
  # is flat: the 12% taken off each side was map, not margin.
  "piece_crop": {},
  # d005 comes off the deck at 1279px, so it sits smaller than the deck
  # pages beside it. The two broker covers pair, black beside white.
  "piece_width": {"drop09": 100, "drop10": 100,
                  "drop04": 60, "drop05": 48, "drop06": 48,
                  "d005": 48, "d006": 48, "d007": 48, "d008": 48,
                  # both cards are small objects and are shown as such
                  "drop02": 30, "drop03": 30,
                  "drop12": 30, "drop13": 30, "drop14": 30},
  "cover": "d004-1",
  "group": "brand", "short": "Real estate marketing design",
  "meta": "Compass, Real Estate Marketing Design",
  "desc": ["As a part of the Compass Real Estate Branding team and under the supervision of Jay Peter Salvas I oversaw the typography and design within the brand's identity, maintained consistency across the projects and designed multiple logos, digital and print collateral for real estate agents.",
           "I worked closely with the Compass marketing team to help Compass Agents to achieve the sales strategy goals through the design. I developed environmental signage for Compass agents and companies affiliated with Compass.",
           "I created print advertisement materials, magazines, brochures, business cards, door hangers. I oversaw brand application, user experience, and user interface for Compass website and email advertisement. I created digital marketing assets, social media, ad banners and email design."],
  "pages": [
    ("D", 4, "The For Sale card", ["brand"]),
    ("D", 5, "Digital banner system", ["brand", "web"]),
    ("D", 6, "Data visualisation – call-out stats", ["brand", "editorial"],
     {"scale": 4.0}),
    ("D", 7, "Data visualisation – inventory tables", ["brand", "editorial"],
     {"scale": 4.0}),
    ("D", 8, "Data visualisation – tables", ["brand", "editorial"],
     {"scale": 4.0}),
    ("IMG", "compass/map.jpg", "245 10th Avenue – neighborhood points of interest", ["brand", "editorial"], {"crop": False}),
  ],
 },
 {
  "slug": "pratt", "title": "Pratt",
  # b087 kept a live browser toolbar, address bar and all.
  "piece_crop": {"b087": (0.075, 0, 0, 0)},
  "year": "2017 to 2020",
  "cover": "b090",
  "group": "book", "short": "Print and institutional identity",
  "meta": "Pratt Institute, Adjunct Professor, 2017 to 2020, Website and Publication Design",
  "desc": ["I developed a brand strategy course for Pratt Institute titled Brand Strategy Design, which is focused on engaging students in critical conversations around innovative strategies in a corporate environment. The brand strategy course I developed at Pratt sought to go beyond traditional branding courses you usually find in design schools that too often focus on a surface understanding of design thinking and logo design.",
           "I initiated and taught Digital Product and Interactive Design course. I created and taught Graphic Design Advanced Senior Project course. I ran workshops and guided individual students, and created course material: syllabi, assignments, presentations, handouts."],
  "pages": [
    ("B", 87, "Pratt Shows – programme index", ["web"], {"dechrome": 120}),  # tab strip + URL bar; taller than the auto-detect finds
    ("B", 88, "Pratt Shows – exhibition page", ["web"], {"dechrome": True}),
    ("B", 89, "Pratt Shows – video art direction", ["brand"]),
    ("B", 90, "Prattfolio – alumni magazine", ["editorial"]),
    ("IMG", "pratt/postcard-yellow.png", "Pratt Shows Spring 2018 – postcard", ["brand", "editorial"], {"crop": False}),
    ("IMG", "pratt/postcard-mint.png", "Pratt Shows Spring 2018 – postcard", ["brand", "editorial"], {"crop": False}),
    ("IMG", "pratt/postcard-pink.png", "Pratt Shows Spring 2018 – postcard", ["brand", "editorial"], {"crop": False}),
  ],
 },
 {
  "slug": "sasha-sedelnikov", "title": "Sasha Sedelnikov",
  "cover": "drop04",
  # The spreads pair off; the posters run three to a row.
  "piece_width": {"drop01": 48, "drop02": 48, "drop03": 48,
                  "drop04": 30, "drop05": 30, "drop06": 30,
                  "drop07": 30, "drop08": 30, "drop09": 30},
  "group": "book", "short": "Publication and show identity",
  "meta": "Sasha Sedelnikov, Publication Design and Show Identity",
  "desc": ["I designed <em>See you later</em>, a photobook by Sasha Sedelnikov held in the Garage Museum of Contemporary Art in Moscow. I paced the monochrome sequences against the colour ones and against the paper, so the images set their own rhythm.",
           "I designed the show identity for <em>Пучки серебряного света</em> (Bundles of Silver Light) at the Museum of the History of Yekaterinburg. The title runs vertically down the poster and each photograph takes the rest of the sheet."],
  "pages": [
    # The folder holds the originals: the book scans at 6392px and the posters
    # at 3508px, where the deck cut them out at about 740.
  ],
 },
 {
  "slug": "sarah-crowner", "title": "Sarah Crowner",
  "year": "2016",
  "layout": "row",
  "captions": False,
  "group": "book", "short": "Monograph design",
  "meta": "Sarah Crowner, Monograph, Publication Design",
  "desc": ["I designed the complete monograph on the painter Sarah Crowner, whose sewn canvases sit between fine and applied art. I designed the cover, the typography, the grid, and the order the essays and plates run in.",
           "Susan Cross's essay <em>Beetle in the Leaves</em> runs tight to the margin against the installation views, while the paintings take full spreads. The layout borrows the logic behind the work, panels butted edge to edge, colour set against colour without a seam."],
  "pages": [
    ("IMG", "sarah-crowner/cover.jpg", "Cover", ["editorial", "brand"], {"split": False, "rotate": 90}),
    ("IMG", "sarah-crowner/beetle-in-the-leaves.jpg", "Beetle in the Leaves – essay opening", ["editorial"], {"split": False, "rotate": -90}),
    ("IMG", "sarah-crowner/standing-totems.jpg", "Standing Totem 1 and 2, 2015 – plates", ["editorial"], {"split": False, "rotate": -90}),
    ("IMG", "sarah-crowner/rotated-commas.jpg", "Experienz #2 and Rotated Commas – figures", ["editorial"], {"split": False, "rotate": -90}),
  ],
 },
 {
  "slug": "dada", "title": "Dada",
  "year": "2016",
  "cover": "charset",
  "group": "type", "short": "Typeface",
  "meta": "Dada, Typeface, Passion Project",
  "kind": "specimen",
  "font": {"family": "Dada", "file": "Dada-Regular",
           "caps": "ACIMOPQRXY", "glyphs": 387, "chars": 370, "year": "2020",
           "sample": "MOMA QUARTZ PARIS",
           "ladder": "DADA IS NOT DEAD, IT SMELLS OF LAUGHTER"},
  "desc": ["A Dada intervention on a grotesque, drawn as capitals and figures only. I cut ten of the twenty six letters, <em>A C I M O P Q R X Y</em>, and redrew them as biomorphic forms after Arp and Taeuber Arp: blobs with eyes, tentacles, stray dots. I left the other sixteen exactly as they were.",
           "Set a word and the typeface behaves. Set a name and it comes apart. <em>QUARTZ</em> keeps its U, its T and its Z, and loses the rest to the shapes. The joke works because the neutral letters stay neutral. The collision does the work, rather than the drawing.",
           "I built it from Helvetica Neue LT Com, whose outlines belong to Linotype. It was a private experiment and I never released it."],
  "pages": [
    ("IMG", "dada/hero.png",     "DADA", ["brand", "editorial"], {"crop": False}),
    ("IMG", "dada/capitals.png", "The ten redrawn capitals", ["brand", "editorial"], {"crop": False}),
    ("IMG", "dada/words.png",    "MOMA, QUARTZ, PARIS", ["brand", "editorial"], {"crop": False}),
    ("IMG", "dada/charset.png",  "The whole set", ["brand", "editorial"], {"crop": False}),
    ("IMG", "dada/setting.png",  "Set at text size, all caps", ["editorial"], {"crop": False}),
    ("IMG", "dada/ladder.png",   "One line at falling sizes", ["editorial"], {"crop": False}),
    ("IMG", "dada/inverted.png", "DADA, reversed", ["brand"], {"crop": False}),
  ],
 },
 {
  "slug": "spiritual-labour", "title": "Spiritual Labour",
  "year": "2014",
  "cover": "charset",
  "group": "type", "short": "Typeface",
  "meta": "Spiritual Labour, Typeface, Passion Project",
  "kind": "specimen",
  "font": {"family": "Spiritual Labour", "file": "SpiritualLabour-Regular",
           "glyphs": 92, "chars": 91, "year": "2014",
           "set": "Capitals and figures",
           "sample": "SPIRITUAL LABOUR",
           "rows": ["ABCDEFGHIJKLM", "NOPQRSTUVWXYZ",
                    "0123456789", "?!.,;:"],
           "ladder": "SPIRITUAL LABOUR"},
  "desc": ["A display face of capitals and figures, drawn as one weight. I cut the letters on a curve rather than a stem. Bowls swell and close, terminals turn back on themselves, and several capitals give up their counters.",
           "Ninety two glyphs. There is no lowercase, so the page sets everything typed into it as capitals."],
  "pages": [
    ("IMG", "spirituallabour/wordmark.png", "The wordmark", ["brand"], {"crop": False}),
    ("IMG", "spirituallabour/charset.png", "Capitals and figures", ["brand"], {"crop": False}),
  ],
 },
 {
  "slug": "isaac-howell", "title": "Isaac Howell",
  "year": "Ongoing",
  # The posters read at a third of the measure rather than a half.
  # The posters read at a third of the measure; the two newspaper spreads are
  # a pair, and the instruction sheet takes a row.
  "piece_width": {"drop01": 48, "drop02": 48, "drop08": 100, "drop09": 30,
                  "drop10": 48, "drop11": 48, "drop03": 34, "drop04": 34,
                  "drop05": 34, "drop06": 34, "drop07": 34},
  "cover": "drop03",
  "group": "book", "short": "Exhibition identity and publication",
  "meta": "Isaac Howell, Exhibition Identity and Publication",
  "desc": ["I designed the identity and the one page publications for solo shows of the artist Isaac Soh Fujita Howell, at Public Gallery in London and at T293 in Rome. For <em>A rabid dog has no choice but to bite</em> the title circles the edge of the poster as a frame, and the painting holds the centre.",
           "Two shows at T293 followed. <em>By order from above (and we are all dutiful citizens)</em> sets the details on overlapping black cards that lock into one another like a puzzle. <em>Malign Influence on the Information Interchange</em> rings the sheet with its own title, then runs the same sheet inverted with photographs set into the ring.",
           "The run extends into newsprint, where the text turns with the page, and into <em>The Man Who Turned into a Wall</em>, which sequences drawings against script."],
  "pages": [
    # Everything comes from drop/isaac-howell/: the print files carry these
    # sheets at 6142px, where the deck cuts them at 1301.
  ],
 },
 {
  "slug": "willow-and-wu", "title": "Willow and Wu",
  "year": "2024",
  "piece_width": {"poster": 42, "b102": 100},
  "piece_crop": {"b100": (0.145, 0, 0.145, 0)},
  "cover": "poster",
  "group": "brand", "short": "Film identity and titles",
  "meta": "Kathy Meng, Film Identity and Titles",
  "desc": ["I designed the identity for <em>Willow and Wu</em>, a short independent film directed by Kathy Meng. A heavy condensed wordmark stacks into a block against the stills, with a full credit line under it.",
           "It carries through the poster and the title sequence on screen."],
  "pages": [
    ("B", 100, "Willow and Wu – wordmark", ["brand"], {"crop": False}),
    ("IMG", "willow-and-wu/poster.png", "Poster design", ["brand"],
     {"crop": False, "split": False}),
    ("B", 102, "Movie titles", ["brand"], {"split": False, "span": 12}),
  ],
 },
 {
  "slug": "literature-paper", "title": "Literature Paper",
  "year": "2016",
  "cover": "drop01",
  "group": "book", "short": "Publication design and concept",
  "meta": "Yale Literature Paper, Publication Design and Concept",
  "desc": ["I designed the first issue of the Yale School of Art literature paper, and set its concept. Cut paper forms in orange, blue and yellow crash through the grid, and the text sets itself into and around the shapes.",
           "Each spread treats its subject as an object to pull apart: a gourd, a garlic house, a table of contents that refuses to sit still."],
  "pages": [
    # The four spreads come from drop/ as flat scans; the deck
    # reproductions of the same pages were lower resolution.
  ],
 },
]
